---
title: "Saving_data_from_NetCDF_to_csv"
author: "Elisa"
date: "2024-08-27"
output: word_document
---

Installing or loading packages
```{r}
rm(list=ls()) # cleans the workspace
#install.packages('RNetCDF')
#install.packages('writexl')
library(RNetCDF)
library(writexl)
```

Opening the NetCDF file
```{r}
data <- open.nc("C:\\Users\\uqegirol\\Desktop\\Secondment\\Accelnet project\\NetCDF_files\\Ridgefield_L6_20160101_20240202.nc", header=TRUE, fill = TRUE) #  imports the file with the data
#print.nc(data)
```
Accessing variable attributes
```{r}
#att.get.nc(data, "Precip", "units")
```
Accessing global attributes
```{r}
#att.get.nc(data, "NC_GLOBAL", "altitude")
```

Getting data out of the file
```{r}
time <- var.get.nc(data, "time")
precipitation <- var.get.nc(data, "Precip")
soil_water_content <- var.get.nc(data, "Sws")
soil_temperature <- var.get.nc(data, "Ts")
air_temperature <- var.get.nc (data, "Ta")
```

Converting dates
```{r}
library(lubridate)
origin_date <- as.Date("1800-01-01") # Define the origin date
days_since_1800 <- time
whole_days <- floor(days_since_1800) # Extract the whole number of days
fractional_day <- days_since_1800 - whole_days # Extract the fractional part of days
date_converted <- origin_date + days(whole_days) # Convert the whole number of days to a Date object

fractional_seconds <- fractional_day * 86400 # multiplies the fractional day for the number of seconds in a day. Returns the number of seconds

posix_converted <- as.POSIXct(date_converted) + fractional_seconds # Create a POSIXct object with the date and fractional seconds

Tz <- att.get.nc(data, "NC_GLOBAL", "time_zone") # extract the time zone
datetime_converted_tz <- as.POSIXct(posix_converted, tz = Tz) # Specify the time zone when creating the POSIXct object. To create a csv file this is commented out because we cannot retain the time zone information in a csv

# Organizing time zone information to be preserved in the csv file
## Saving time zone to a separate column
library(dplyr)
time_zone <- rep(Tz, length(posix_converted))
```

Saving to a dataframe
```{r}
df <- data.frame(Time = datetime_converted_tz, Time_zone = time_zone, Precipitation = precipitation, Soil_water_content = soil_water_content, Soil_temperature = soil_temperature, Air_temperature = air_temperature)

# Convert POSIXct to character
df$Time <- format(df$Time, format = "%Y-%m-%d %H:%M:%S")
```

Same example plots to check the data
```{r}
#plot(df$Air_temperature, df$Soil_temperature)
#plot(df$Precipitation, df$Soil_water_content)
#plot(posix_converted, df$Air_temperature)
```

Saving to a csv file
```{r}
write_xlsx(df, "C:\\Users\\uqegirol\\Desktop\\Secondment\\Accelnet project\\NetCDF_files\\Ridgefield_L6_20160101_20240202.csv")
```